basePath: /v1
consumes:
- application/json
info:
  description: API para la gestión de lógica de observatorios
  title: observatorios_mid
  version: '1.0'
paths: {}
produces:
- application/json
responses:
  MaskError:
    description: When any error occurs on mask
  ParseError:
    description: When a mask can't be parsed
swagger: '2.0'
tags: []
